version: "3"
services:
  employee-api:
    build: .
    ports:
      - "4001:4001"
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=data_kepegawaian
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_kepegawaian
    ports:
      - "5432:5432"
